### ISSUE TITLE
ValueError from xcontest igc file

### ISSUE THREAD

**Issue by luigichelli** [OverloadUT/IGC2CSV#4]
Hello there, I'm having the following error... any idea? thanks!

Traceback (most recent call last):
  File "igc2csv.py", line 253, in <module>
    flight = parse_igc(flight)
  File "igc2csv.py", line 16, in parse_igc
    recordtypes[linetype](line, flight)
  File "igc2csv.py", line 101, in logline_H
    headertypes[line[1:5]](line[5:], flight)
  File "igc2csv.py", line 110, in logline_H_FDTE
    flight['flightdate'] = datetime.date(int(line[4:6])+2000, int(line[2:4]), int(line[0:2]))
ValueError: invalid literal for int() with base 10: ':0'

**Comment by ScottStanton** [comment]
Change line 110 to:
  flight['flightdate'] = datetime.date(int(line[9:11])+2000, int(line[7:9]), int(line[5:7]))

**Comment by ScottStanton** [comment]
I fixed it in my fork of the code.  Feel free to commit my changes.  
https://github.com/ScottStanton/IGC2CSV

**Comment by syunusic** [comment]
Hi! I had the same problem... this is what happened the first time I run it:
```
$ python2 IGC2CSV.py /tmp/230325175253.igc 
Number of arguments: 2
Argument List: ['IGC2CSV.py', '/tmp/230325175253.igc']
Single IGC file supplied: /tmp/230325175253.igc
1 flights ready to process...
Traceback (most recent call last):
  File "IGC2CSV.py", line 254, in <module>
    flight = parse_igc(flight)
  File "IGC2CSV.py", line 16, in parse_igc
    recordtypes[linetype](line, flight)
  File "IGC2CSV.py", line 101, in logline_H
    headertypes[line[1:5]](line[5:], flight)
  File "IGC2CSV.py", line 110, in logline_H_FDTE
    flight['flightdate'] = datetime.date(int(line[4:6])+2000, int(line[2:4]), int(line[0:2]))
ValueError: invalid literal for int() with base 10: ':2'
```
Then I change line 110 as @ScottStanton suggested and this is the error I got now:
```
$ python2 IGC2CSV.py /tmp/230325175253.igc 
  File "IGC2CSV.py", line 111
    flight['flightdate'] = datetime.date(int(line[9:11])+2000, int(line[7:9]), int(line[5:7]))
         ^
IndentationError: expected an indented block
```
Please help!

**Comment by ScottStanton** [comment]
Can you post lines 107 to 114 from your code?

**Comment by syunusic** [comment]
Sure:
```
# Date format: DDMMYY
# (did we learn nothing from Y2K?)
def logline_H_FDTE(line, flight):
#  flight['flightdate'] = datetime.date(int(line[4:6])+2000, int(line[2:4]), int(line[0:2]))
flight['flightdate'] = datetime.date(int(line[9:11])+2000, int(line[7:9]), int(line[5:7]))
  print "Flight date: {}".format(flight['flightdate'])



```

**Comment by ScottStanton** [comment]
Indent the line that start with 'flight' to match the indentation of the 'print' below it.
Python is very particular about indentation.

**Comment by syunusic** [comment]
Wow... that was it. Thanks!
